---
title: "Replication of **Some General Guidelines for Choosing Missing Data Handling Methods in Educational Research** by Cheema (2014, Journal of Modern Applied Statistical Methods)"
author: "Radhika Kapoor (rkap786@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

###Project proposal 
(1) Reproduce empirical findings  from Cheema 2014 as applied to PISA 2003, and (2) Replicate the findings for another education dataset (PISA 2006)

####Justification

Cheema (2014) evaluates different treatment methods for missing data in survey data and provides their effect on accuracy of estimation. The paper conducts the analysis on 
  (1) simulated dataset (n=10,000 cases) 
  (2) real-world empirical samples: (a) US portion of PISA 2003 (n=456 cases);(b)        Population and Housing portion of US Census (2000)

I plan to replicate 2(a). This paper is relevant to my research interests as I plan to work on large datasets, and by replicating the results, I'd learn how to handle missing data in future work. It'd also give me an opportunity to work with large-scale assessment datasets that I want to work on in the future. 


####Procedure for replication
For the replication, I would have to access the PISA datasets, understand their structure and apply the methods described in the paper: listwise deletion, mean imputation, regression imputation, EM imputation and Multiple imputation. 

The challenges in the project would be: (1) accessing PISA datasets by country - they're supposed to be available online, I need to confirm the datasets have all the required variables. If PISA is not available, I have access to the Annual Survey of Education Report (ASER) 2011 data that I could use, but the underlying structure of the data is different from PISA, so it would not be an exact replication (2) Figuring out how to code the methods used in the paper

####Links
Link to the repo: https://github.com/psych251/cheema2014
Link to the original paper:https://github.com/psych251/cheema2014/tree/master/original_paper




[No abstract is needed.]  Each replication project will have a straightforward, no frills report of the study and results.  These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of data collection.  Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for replication, and any other essential information.  It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.  


##Methods

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

###Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
